# schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Historique de commandes de Greenwizz avec les revenus et les quantités
        columns:
          - name: revenue 
            description: total revenue from the sales
      - name: product
        identifier: raw_gz_product
        description: Identifation d'un prix fonction du product_id
      - name: ship
        identifier: raw_gz_ship
        description: Tables des coûts liés aux shipping
