# schema.yml

version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Historique de commandes de Greenwizz avec les revenus et les quantités
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after:
            count: 90
            period: day
        columns:
          - name: date_date
            description: date of purchase
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

      - name: product
        identifier: raw_gz_product
        description: Identifation d'un prix fonction du product_id
        columns:
          - name: products_id
            description: Primary Key
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: Tables des coûts liés aux shipping
        columns:
          - name: orders_id
            description: identifiant de commande
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords
        description: Retour de campagne Adwords, ads_cost, impressions, click
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: site
          - name: campaign_key
            description: code de numéro de campagne
          - name: campgn_name
            description: nom codé de la campagne
          - name: ads_cost
            description: prix de la campagne pub
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

 
      - name: bing
        identifier: raw_gz_bing
        description: Retour de campagne bing, ads_cost, impressions, click
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: site
          - name: campaign_key
            description: code de numéro de campagne
          - name: campgn_name
            description: nom codé de la campagne
          - name: ads_cost
            description: prix de la campagne pub
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

      - name: criteo
        identifier: raw_gz_criteo
        description: Retour de campagne criteo, ads_cost, impressions, click
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: site
          - name: campaign_key
            description: code de numéro de campagne
          - name: campgn_name
            description: nom codé de la campagne
          - name: ads_cost
            description: prix de la campagne pub
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

      - name: facebook
        identifier: raw_gz_facebook
        description: Retour de campagne facebook, ads_cost, impressions, click
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: site
          - name: campaign_key
            description: code de numéro de campagne
          - name: campgn_name
            description: nom codé de la campagne
          - name: ads_cost
            description: prix de la campagne pub
          - name: impression
            description: nombre d'impression
          - name: click
            description: nombre de click
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"


models:
  - name: int_orders_margin
    description: table intermediaire des orders margins, fait à partir de la table sales
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
          
  - name: int_orders_operational
    description: table intermediaire faite à partir des stg_raw_ship
    columns:
      - name: orders_id
        tests:
         - unique
         - not_null

  - name: int_sales_margin
    description: table intermediaire faite à partir des stg_raw_sales et stg_raw_product
    tests:
      - unique:
          column_name: "(orders_id || '_' || products_id)"

  - name: finance_days
    description: table finale présentée aux équipes BI finance
    columns:
      - name: date_date
        tests:
          - unique
          - not_null

  - name: int_campaigns
    description: table intermediaire faite à partir des fichiers brut de chaque marques publicitaires
    tests:
      - unique:
          column_name: "(date_date || '_' || campaign_key)"

  - name: int_campaigns_day
    description: view des aggrégations par jour des clicks / impressions / coûts des pubs
    columns:
      - name: date_date
        tests:
          - unique
          - not_null


